In [5]:
pip install datasets

Collecting datasets
  Using cached datasets-2.4.0-py3-none-any.whl (365 kB)
Collecting huggingface-hub<1.0.0,>=0.1.0
  Using cached huggingface_hub-0.9.1-py3-none-any.whl (120 kB)
Requirement already satisfied: pandas in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from datasets) (1.3.5)
Collecting pyarrow>=6.0.0
  Downloading pyarrow-9.0.0-cp37-cp37m-macosx_10_13_x86_64.whl (23.9 MB)
     |████████████████████████████████| 23.9 MB 5.5 MB/s eta 0:00:01
Collecting tqdm>=4.62.1
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting dill<0.3.6
  Using cached dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
Collecting multiprocess
  Downloading multiprocess-0.70.13-py37-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 4.4 MB/s eta 0:00:01
Collecting responses<0.19
  Using cached responses-0.18.0-py3-none-any.whl (38 kB)
Collecting xxhash
  Downloading xxhash-3.0.0-cp37-cp37m-macosx_10_9_x86_64.whl (34 kB)
Requirement already satisfied: packaging in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from datasets) (21.3)
Collecting aiohttp
  Downloading aiohttp-3.8.1-cp37-cp37m-macosx_10_9_x86_64.whl (570 kB)
     |████████████████████████████████| 570 kB 3.5 MB/s eta 0:00:01
Requirement already satisfied: importlib-metadata in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from datasets) (4.11.3)
Requirement already satisfied: numpy>=1.17 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from datasets) (1.21.5)
Collecting requests>=2.19.0
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 3.4 MB/s eta 0:00:01
Collecting fsspec[http]>=2021.11.1
  Using cached fsspec-2022.7.1-py3-none-any.whl (141 kB)
Collecting filelock
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets) (4.1.1)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp37-cp37m-macosx_10_9_x86_64.whl (189 kB)
     |████████████████████████████████| 189 kB 4.8 MB/s eta 0:00:01
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from packaging->datasets) (3.0.4)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from requests>=2.19.0->datasets) (2022.6.15)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 4.1 MB/s eta 0:00:01
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.5 MB/s eta 0:00:01
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.1-cp37-cp37m-macosx_10_9_x86_64.whl (36 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp37-cp37m-macosx_10_9_x86_64.whl (28 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.1-cp37-cp37m-macosx_10_9_x86_64.whl (60 kB)
     |████████████████████████████████| 60 kB 3.7 MB/s eta 0:00:01
Requirement already satisfied: zipp>=0.5 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from importlib-metadata->datasets) (3.8.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from pandas->datasets) (2021.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/tf/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.16.0)
Installing collected packages: multidict, idna, frozenlist, yarl, urllib3, charset-normalizer, attrs, asynctest, async-timeout, aiosignal, tqdm, requests, pyyaml, fsspec, filelock, dill, aiohttp, xxhash, responses, pyarrow, multiprocess, huggingface-hub, datasets
Successfully installed aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 asynctest-0.13.0 attrs-22.1.0 charset-normalizer-2.1.1 datasets-2.4.0 dill-0.3.5.1 filelock-3.8.0 frozenlist-1.3.1 fsspec-2022.7.1 huggingface-hub-0.9.1 idna-3.3 multidict-6.0.2 multiprocess-0.70.13 pyarrow-9.0.0 pyyaml-6.0 requests-2.28.1 responses-0.18.0 tqdm-4.64.0 urllib3-1.26.12 xxhash-3.0.0 yarl-1.8.1
Note: you may need to restart the kernel to use updated packages.

In [7]:
import datasets
data = datasets.load_dataset("glue", "cola")
data

/opt/anaconda3/envs/tf/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Reusing dataset glue (/Users/yenaahn/.cache/huggingface/datasets/glue/cola/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
100%|██████████| 3/3 [00:00<00:00, 547.51it/s]

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 8551
    })
    validation: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1043
    })
    test: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1063
    })
})

In [8]:
import pandas as pd
import numpy as np

In [9]:
train = pd.DataFrame(data['train'])
test = pd.DataFrame(data['test'])
valid = pd.DataFrame(data['validation'])
display(train,test,valid)

                                               sentence  label   idx
0     Our friends won't buy this analysis, let alone...      1     0
1     One more pseudo generalization and I'm giving up.      1     1
2      One more pseudo generalization or I'm giving up.      1     2
3        The more we study verbs, the crazier they get.      1     3
4             Day by day the facts are getting murkier.      1     4
...                                                 ...    ...   ...
8546                   Poseidon appears to own a dragon      0  8546
8547                     Digitize is my happiest memory      0  8547
8548                     It is easy to slay the Gorgon.      1  8548
8549       I had the strangest feeling that I knew you.      1  8549
8550                What all did you get for Christmas?      1  8550

[8551 rows x 3 columns]

                                               sentence  label   idx
0                         Bill whistled past the house.     -1     0
1                 The car honked its way down the road.     -1     1
2                       Bill pushed Harry off the sofa.     -1     2
3                  the kittens yawned awake and played.     -1     3
4     I demand that the more John eats, the more he ...     -1     4
...                                                 ...    ...   ...
1058         John thinks it would upset himself to die.     -1  1058
1059                  John made Bill be mad at himself.     -1  1059
1060  John knew that the book for himself to read wa...     -1  1060
1061  John knew that for himself to be there would c...     -1  1061
1062              A picture of himself frightened John.     -1  1062

[1063 rows x 3 columns]

                                               sentence  label   idx
0       The sailors rode the breeze clear of the rocks.      1     0
1     The weights made the rope stretch over the pul...      1     1
2            The mechanical doll wriggled itself loose.      1     2
3           If you had eaten more, you would want less.      1     3
4              As you eat the most, you want the least.      0     4
...                                                 ...    ...   ...
1038                         John considers Bill silly.      1  1038
1039                   John considers Bill to be silly.      1  1039
1040        John bought a dog for himself to play with.      0  1040
1041        John arranged for himself to get the prize.      1  1041
1042                 John talked to Bill about himself.      1  1042

[1043 rows x 3 columns]

In [10]:
all_data = pd.concat([train, test, valid])
all_data = all_data.iloc[:,:-1]
all_data

                                               sentence  label
0     Our friends won't buy this analysis, let alone...      1
1     One more pseudo generalization and I'm giving up.      1
2      One more pseudo generalization or I'm giving up.      1
3        The more we study verbs, the crazier they get.      1
4             Day by day the facts are getting murkier.      1
...                                                 ...    ...
1038                         John considers Bill silly.      1
1039                   John considers Bill to be silly.      1
1040        John bought a dog for himself to play with.      0
1041        John arranged for himself to get the prize.      1
1042                 John talked to Bill about himself.      1

[10657 rows x 2 columns]

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer
tk = Tokenizer()
tk.fit_on_texts([all_data['sentence']])
print(tk.word_index)

AttributeError: 'Series' object has no attribute 'lower'